### ISSUE TITLE
[BUG]: where is the "examples/experiment_eval.py"?

### ISSUE THREAD

**Issue by LiuYuHan31** [sotopia-lab/sotopia#1]
### Description of the bug

hi, I try to run the following code :
python examples/experiment_eval.py --gin_file sotopia_conf/generation_utils_conf/generate.gin --gin_file sotopia_conf/server_conf/server.gin --gin_file sotopia_conf/run_async_server_in_batch.gin '--gin.ENV_IDS=["01H7VFHPDZVVCDZR3AARA547CY"]' '--gin.AGENT1_MODEL="gpt-4"' '--gin.BATCH_SIZE=20' '--gin.PUSH_TO_DB=False' '--gin.TAG="test"
but I find that there are some errors because the lack of "examples/experiment_eval.py".
If I want to run the code quickly to try the demo(run the experiment_eval.py), what should I do?

Thanks for your time!

### Steps To Reproduce

1.run python examples/experiment_eval.py --gin_file sotopia_conf/generation_utils_conf/generate.gin --gin_file sotopia_conf/server_conf/server.gin --gin_file sotopia_conf/run_async_server_in_batch.gin '--gin.ENV_IDS=["01H7VFHPDZVVCDZR3AARA547CY"]' '--gin.AGENT1_MODEL="gpt-4"' '--gin.BATCH_SIZE=20' '--gin.PUSH_TO_DB=False' '--gin.TAG="test"
2. errors

**Comment by ProKil** [comment]
@LiuYuHan31 Thanks for your issue. We will add the eval script back.

**Comment by weikang-wang** [comment]
same problem

**Comment by XuhuiZhou** [comment]
Hi, `experiment_eval.py` is added to the `examples` folder! Let me know if you have any more questions.
