### ISSUE TITLE
[BUG]: Data is not available 

### ISSUE THREAD

**Issue by changhongyan123** [sotopia-lab/sotopia#10]
### Description of the bug

Hi, thanks for the interesting work and your contribution to making this library. I tried to run the example based on my macOS and Ubuntu, but neither worked for me. The command is what is provided in the readme:
```
python -m sotopia_conf.server --gin_file="sotopia_conf/server_conf/server.gin" --gin_file="sotopia_conf/generation_utils_conf/generate.gin"
```

The error I am getting is as follows:
```
IndexError: Cannot choose from an empty sequence
```

After investigation, I found that it may be because my Redis database is empty. If that is the case, may I know if the data will be available or if we need to create the agents, tasks, and environment by ourselves?

<img width="999" alt="image" src="https://github.com/sotopia-lab/sotopia/assets/17850808/a5b532d9-adf9-4344-9e5f-ba0c69b5893d">

### Steps To Reproduce

1. Install the repository 
2. Install the dependent packages as suggested in the readme. 
3. Run `python -m sotopia_conf.server --gin_file="sotopia_conf/server_conf/server.gin" --gin_file="sotopia_conf/generation_utils_conf/generate.gin"`

**Comment by XuhuiZhou** [comment]
Please refer to this issue for the data, let me know if you have any more questions.

https://github.com/sotopia-lab/sotopia/issues/7#issuecomment-1806365778

**Comment by changhongyan123** [comment]
Thank you for your help. It works now.
