### ISSUE TITLE
[FEAT]: Get rid of float for rewards in Episodelog

### ISSUE THREAD

**Issue by XuhuiZhou** [sotopia-lab/sotopia#13]
### Description

```
rewards: list[
        tuple[float, dict[str, float]] | float
    ]  # Rewards arranged by turn
```
@ProKil Any chance we can get rid of float option for the rewards? I think this setting here is causing a lot of issues and getting rid of it could make the repo cleaner.

**Comment by ProKil** [comment]
In the current released database in #7, we use [0.0, 0.0] to indicate that the evaluator fails to respond. How do you want to:

1. represent these cases? 
2. migrate the current released database?

**Comment by XuhuiZhou** [comment]
Yeah yeah, good Qs, here are my thoughts: 
1. If the episodes fail, maybe we should not include them in the first place to the database? The trouble comes later if we allow the failed episodes coming to the database. And choosing not to include them at the first place makes a lot easier to fix those problematic episodes imo.
2. I suppose we can update the release?

**Comment by ProKil** [comment]
For 1. I would prefer an alternative: `list[tuple[float, dict[str, float]]] | None`. In this way, we can represent both episodes with legal rewards, and the ones without (b/c evaluator failure or we want to give rewards later)

**Comment by XuhuiZhou** [comment]
Yeah, I like this better, at least `None` is a better state to assert.

**Comment by XuhuiZhou** [comment]
Solved; Now people should use the `get_reward` function to ensure the rewards are there!
