### ISSUE TITLE
[BUG]: Error occurred while executing minimalist_demo.py

### ISSUE THREAD

**Issue by Kong-Aobo** [sotopia-lab/sotopia#144]
### Description of the bug

I followed the steps in README.md to install sotopia and redis, then set up the OpenAI key. After that, I ran minimalist_demo.py directly and encountered an error as follows:
```
File "/mnt/workspace/sotopia/sotopia/server.py", line 294, in run_async_server
    episode_futures = [
                      ^
  File "/mnt/workspace/sotopia/sotopia/server.py", line 294, in <listcomp>
    episode_futures = [
                      ^
  File "/mnt/workspace/sotopia/sotopia/samplers/uniform_sampler.py", line 55, in sample
    env_profile_id = random.choice(list(EnvironmentProfile.all_pks()))
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/workspace/anaconda/envs/sotopia/lib/python3.11/random.py", line 370, in choice
    raise IndexError('Cannot choose from an empty sequence')
```
Actually, this is also mentioned in another issue (#10). However, I failed to download the data:
```
(sotopia) /mnt/workspace/sotopia> curl -L https://cmu.box.com/shared/static/xiivc5z8rnmi1zr6vmk1ohxslylvynur --output data/dump.rdb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:02:11 --:--:--     0
curl: (28) Failed to connect to cmu.app.box.com port 443 after 130213 ms: Connection timed out
```
So my question is:

1. How can I get the data?
2. After I download the data, where should I put them to make minimalist_demo.py run successfully?

If my understanding is correct, the relevant statements in README.md are missing some important information. I hope you can complete the documentation to make it easier for newcomers.

By the way, I want reproduce the SOTOPIA paper, what should I do? Some information is provided in README.md but it seems that no documents exist in ./docs.
```
For the original Sotopia simulation in our paper's experiments, you can find how to get them in the [Q&A](https://github.com/sotopia-lab/sotopia/blob/main/docs/troubleshooting.md) section in the ./docs folder.
```

Thanks for your help. I will also read the code to improve my understanding.

### Steps To Reproduce

Related info has been provided above.

**Comment by ProKil** [comment]
Thank you for raising the issue, and I am sorry for the documentation problem. The documentation is currently the priority of the team as mentioned in #70. 

Since #122, please use the following two steps to install sotopia:

```bash
pip install sotopia
sotopia install # You will be prompted to download data interactively
```

Please let me know if this works for you.

**Comment by Kong-Aobo** [comment]
Due to network issues, I chose to install manually （I tried your solution and I have known its effects）. I have downloaded the file (https://cmu.box.com/shared/static/xiivc5z8rnmi1zr6vmk1ohxslylvynur.) and placed it in the folder (/mnt/workspace/redis-stack-server-7.2.0-v10/var/db/redis-stack). However, I still get the same error when I run minimalist_demo.py (its path is /mnt/workspace/sotopia/examples). So I guess the problem is that the relative position of the redis folder and minimalist_demo.py is wrong？

**Comment by ProKil** [comment]
Since the Redis stack server is a different process from sotopia, the relative position doesn't matter. Have you started the redis server?

**Comment by Kong-Aobo** [comment]
Please forgive me for bothering you again. In addition to the above question, I would like to ask you again for help on how to reproduce the original paper (I would be very grateful if you can explain it clearly in this issue first). In my personal opinion, how to reproduce the original paper should be the first thing that the document should improve, rather than some custom behavior.

**Comment by ProKil** [comment]
> Please forgive me for bothering you again. In addition to the above question, I would like to ask you again for help on how to reproduce the original paper (I would be very grateful if you can explain it clearly in this issue first). In my personal opinion, how to reproduce the original paper should be the first thing that the document should improve, rather than some custom behavior.

Sure. Can you let me know which part you want to reproduce? Based on the database we released, you can calculate all of the correlations and evaluation results with the existing data. If you want generate new data (new episodes or scenarios), I can also help you with that.

**Comment by Kong-Aobo** [comment]
Thanks for your patience. I want to reproduce the SOTOPIA paper (ICLR 2023). Specifically, I would like to replicate the results of any pair of agents (including GPT-4, GPT-3.5, Llama-3-80B, etc.) on both the full SOTOPIA and SOTOPIA-Hard environments. I am very familiar with fastchat and vllm.

**Comment by Kong-Aobo** [comment]
> Since the Redis stack server is a different process from sotopia, the relative position doesn't matter. Have you started the redis server?
I've resolved the issue. The .rdb file must be named dump.rdb. After making this change, the program runs smoothly. I don't know whether to laugh or cry. Thanks for your help again.

**Comment by ProKil** [comment]
Cool, I will edit the documentation to emphasize the importance of naming the rdb file.
