### ISSUE TITLE
[FEAT]: Preview doc deployment

### ISSUE THREAD

**Issue by ProKil** [sotopia-lab/sotopia#145]
### Description

Currently, all of the doc improvements are made in the `dev` branch. But this is hard for people to contribute to various parts of the documentation together. 

Let's use [this Github Action](https://github.com/rossjrw/pr-preview-action) to preview Github page deployment.

**Comment by XuhuiZhou** [comment]
oh I like this, could we do a similar thing for our sotopia website?

**Comment by ProKil** [comment]
sotopia website is handled by vercel? If we use a similar way to the docs site, we should be able to use this for that as well.

**Comment by XuhuiZhou** [comment]
Yeah, I am going to move it to github pages

**Comment by ProKil** [comment]
Sadly, after some digging, I found that the action above doesn't support actions/deploy-page (deploy from github action). 

And the preview feature of actions/deploy-page is still in alpha: https://github.com/actions/deploy-pages/issues/337.
