### ISSUE TITLE
[FEAT]: Support system prompt in Sotopia

### ISSUE THREAD

**Issue by XuhuiZhou** [sotopia-lab/sotopia#149]
### Description

System prompts have been a standard practice for many models.
* https://platform.openai.com/docs/guides/prompt-engineering/tactic-ask-the-model-to-adopt-a-persona
* https://llama.meta.com/docs/model-cards-and-prompt-formats/meta-llama-3/
* https://api.python.langchain.com/en/latest/messages/langchain_core.messages.system.SystemMessage.html

We should enable Sotopia to support that.

**Comment by ProKil** [comment]
Can you make this clearer? In which function do you want to use the system message? And how would that argument be passed into the generation function?

**Comment by XuhuiZhou** [comment]
we don't need this now! system prompt should not exist in the simulation.
