### ISSUE TITLE
[FEAT]: Sotopia API for Social Science

### ISSUE THREAD

**Issue by XuhuiZhou** [sotopia-lab/sotopia#151]
### Description

API parameters
* characters profiles; 
* goals
* scenario description
* action space
* secrets
* customized evaluation prompts

**Comment by ProKil** [comment]
Which API? Which parameters? Please include more concrete description of the feature requested.

**Comment by XuhuiZhou** [comment]
It's more like a fastAPI ish thing that people can just run simulation wo installing sotopia

**Comment by ProKil** [comment]
It sounds cool, but please make it clearer? What are the input args and their types? What is the expected behavior?
