### ISSUE TITLE
[FEAT]:  Specific steps of reproducing SOTOPIA (ICLR 2024) paper

### ISSUE THREAD

**Issue by Kong-Aobo** [sotopia-lab/sotopia#155]
### Description

Here I am again , submitting another issue. I have read through part of the code, as well as the contents in the examples and script folders. It seems that run_interaction.sh is the script closest to reproducing SOTOPIA (ICLR2024). However, I am still not entirely sure, so I hope you could provide the specific script or command to reproduce the data in the GPT-4 column of Table 2 (ICLR 2024) (namely results of GPT4 with GPT4, GPT3.5, etc ). Or, perhaps you could first provide an example of implementing the interaction between GPT-4 and GPT-3.5 on SOTOPIA (ICLR 2024), and I will modify it for other models myself. Thanks for your help.

**Comment by ProKil** [comment]
@XuhuiZhou will help with this.

**Comment by XuhuiZhou** [comment]
@Kong-Aobo we didn't maintain a bash script for Sotopia (ICLR 2024)
All the bash scripts are for https://arxiv.org/abs/2403.05020
To initiate an interaction, please follow the https://docs.sotopia.world/

**Comment by Kong-Aobo** [comment]
@XuhuiZhou First, thanks for your response. Following your guide, to reproduce the ICLR 2024 paper, I found /cli/benchmark/benchmark.py and ran it successfully. I discovered that the Python file only supports running on the hard subset, so I modified the file to support the complete SOTOPIA dataset (which includes 450 tasks). I have a question to confirm with you: 

+ If I want to test a model's capability on the full dataset, this model should play the role of each agent in each of the 450 tasks (each task includes a pair of agents) once. In other words, evaluating this model should generate 900 episodes. Is my understanding correct?

**Comment by XuhuiZhou** [comment]
Yes, I think that's correct. Yeah, for the benchmark.py script, it only supports hard set for now. Good to see that you modified it to the complete set. If you want, feel free to make a pull request to include an argument to switch between hard and full sets.
