### ISSUE TITLE
[FEAT]: Remove all_pks from UniformSampler

### ISSUE THREAD

**Issue by ProKil** [sotopia-lab/sotopia#159]
### Description

https://github.com/sotopia-lab/sotopia/blob/be6c333c8ffeb8e370fead8abddc676f85e54656/sotopia/samplers/uniform_sampler.py#L55

is the only place we use `all_pks`, which could be slow when the number of keys is large since it is using `scan_its` which sends a request to the database for each key. 

We can replace it with keys + random choice.

**Comment by XuhuiZhou** [comment]
run
`start_time = time.time();[i for i in EnvironmentProfile.all_pks()];print("--- %s seconds ---" % (time.time() - start_time))`
I got
--- 269.12071681022644 seconds ---

Which is very unlikely simply caused by the east-west coast internet latency?
https://wondernetwork.com/pings/Pittsburgh/Seattle

**Comment by ProKil** [comment]
Maybe we can profile it to see where the time is spent. I got 76.58491492271423 seconds for your command from a Pittsburgh IP to a Pittsburgh redis server (on a different machine), and 0.78 seconds for your command from my machine to localhost.

**Comment by ProKil** [comment]
If the above is also the case for you, one way to resolve this is through pipelining, which means we issue bulk instructions. This is not supported by Redis-om and I will have to dependency inject a new function to the Json Model they have.

**Comment by XuhuiZhou** [comment]
Running
```
from redis import Redis
import os
import time
from sotopia.database import EnvironmentProfile
redis = Redis.from_url(os.environ["REDIS_OM_URL"])
print("connecting to redis...", os.environ["REDIS_OM_URL"])
start_time = time.time();redis.ping();print("--- %s seconds for each ping ---" % (time.time() - start_time))

start_time = time.time()
environment_pks = [i for i in EnvironmentProfile.all_pks()]
print("number of environment profiles: ", len(environment_pks))
print("--- %s seconds for loading the whole env profile ---" % (time.time() - start_time))
```
Note that the database is on midnights, which is a Pittsburgh-based server.

![image](https://github.com/user-attachments/assets/fc99ef73-576f-46c3-926a-3e79b355df1f)

**Comment by XuhuiZhou** [comment]
```
from redis import Redis
import os
import time
from sotopia.database import EnvironmentProfile
redis = Redis.from_url(os.environ["REDIS_OM_URL"])
print("connecting to redis...", os.environ["REDIS_OM_URL"])
start_time = time.time();redis.ping();print("--- %s seconds for each ping ---" % (time.time() - start_time))

# start_time = time.time()
# environment_pks = [i for i in EnvironmentProfile.all_pks()]
# print("number of environment profiles: ", len(environment_pks))
# print("--- %s seconds for loading the whole env profile ---" % (time.time() - start_time))


start_time = time.time()
environment_pks = list(open("envs.txt").read().split("\n"))
for pk in environment_pks:
    envs = EnvironmentProfile.get(pk)
print("--- %s seconds for loading each env profile ---" % (time.time() - start_time))
```

![image](https://github.com/user-attachments/assets/761ebcdb-1223-4604-93d4-7e73f68dd996)
Once we have the pks, things are actually blazing fast

**Comment by XuhuiZhou** [comment]
```
start_time = time.time()
environment_pks = list(open("envs.txt").read().split("\n"))
for pk in environment_pks:
    env_agent_combo = EnvAgentComboStorage.find(EnvAgentComboStorage.env_id == pk).all() 
print("--- %s seconds for loading each env profile ---" % (time.time() - start_time))
```
![image](https://github.com/user-attachments/assets/4e4e378f-283c-4c9c-baeb-e6b7ac32b0c8)

**Comment by XuhuiZhou** [comment]
Actually, I found this works.
`EnvAgentComboStorage.find().all()`

I check the redis doc about om as well (https://redis.io/docs/latest/integrate/redisom-for-python/#find-people-using-full-text-search-on-their-personal-statements)

basically we should not use `all_pks()`?

**Comment by ProKil** [comment]
Sounds good! I think `find().all()` will also block the server, but for sotopia use case it should be fine I think as long as it is use sparingly.

**Comment by ProKil** [comment]
Do you want to update the PR?
