### ISSUE TITLE
[FEAT]: gpt-4o as the evaluater

### ISSUE THREAD

**Issue by Kong-Aobo** [sotopia-lab/sotopia#178]
### Description

In the sotopia paper (ICLR 2024), GPT-4 was used as the evaluation model. If we switch the evaluation model to GPT-4o, will the evaluation performance improve, remain the same, or decline? Do you have any latest research updates that you can share? Or would you recommend switching the evaluation model to GPT-4o?

**Comment by XuhuiZhou** [comment]
We've tested GPT-4o, which does not significantly improve the performance yet not worse either. @bugsz can further confirm. 
That being said, I would probably recommend using GPT-4o since it's faster.

**Comment by Kong-Aobo** [comment]
Thanks for your answer and patience. By the way, today I came across SotopiaDimensionsPlus, would replacing SotopiaDimensions with it result in any performance gains in terms of evaluation?

**Comment by bugsz** [comment]
These detailed prompts are [additional exps in rebuttal](https://openreview.net/forum?id=mM7VurbA4r&noteId=rUggcH3LOs). According to the resutls, there seems to be no significant improvement

**Comment by Kong-Aobo** [comment]
All questions are solved. Thanks again.
