### ISSUE TITLE
[FEAT]: How is the base profiles generated?

### ISSUE THREAD

**Issue by winnie0617** [sotopia-lab/sotopia#244]
### Description

Hi! I noticed the function `agenerate_init_profile` expands a collection of base profiles. I am wondering if the code for generating these profiles (or the profiles themselves) can be shared. Thank you!

**Comment by XuhuiZhou** [comment]
we don't have further code for generating profiles, please check the original sotopia paper, in which we basically use the `agenerate_init_profile` to get the initialization of profiles and then manually edit those. Feel free to reopen the issue if you have more questions.
