### ISSUE TITLE
[FEAT]: Adding models for benchmarking

### ISSUE THREAD

**Issue by clementou** [sotopia-lab/sotopia#29]
### Description

TogetherAI models:
- [x] Yi-34B-Chat
- [x] Qwen-14B-Chat
- [x] WizardLM-13b-v1.2
- [x] Mistral-7b-Instruct-v0.2
- [x] deepseek-coder-33b-instruct
- [x] Vicuna v1.5 (13B)
- [x] CodeLlama-34B-Instruct
- [x] OpenHermes-2.5-Mistral-7B
- [x] openchat_3.5
- [x] alpaca (7B)
- [x] falcon-40b-instruct
- [x] StripedHyena-Nous-7B

Hugging Face models:
- [ ] Tulu-2-DP0-70B
- [ ] Dolphin-2.2.1-Mistral-7B
- [ ] Dolly-V2-12B
- [ ] deepseek-llm-67b-chat
- [ ] Zephyr-7b-beta
- [ ] Zephyr-7b-alpha
- [ ] FastChat-T5-3b
- [ ] WizardLM-70B-v1.0
- [ ] gpt4all-13b-snoozy
- [ ] oasst-sft-4-pythia-12b-epoch-3.5
- [ ] stablelm-tuned-alpha-7b
- [ ] Starling-LM-7B-alpha
- [ ] koala-13b-HF
- [ ] guanaco-33b-merged
- [ ] SOLAR-10.7B-Instruct-v.10

[Tsinghua](https://open.bigmodel.cn/dev/howuse/introduction):
- [ ] chatglm4
- [ ] chatglm3-6b
- [ ] chatglm2-6b
- [ ] chatglm-6b

FastChat:
- [ ] Vicuna-33B

Nvidia:
- [ ] Llama2-70B-SteerLM-Chat

- [ ] rwkv-6-eagle

### Proprietary:
[Anthropic](https://docs.anthropic.com/claude/reference/selecting-a-model):
- [ ] Claude-1
- [ ] Claude-2.0
- [ ] Claude-2.1
- [ ] Claude-Instant-1

[Google](https://cloud.google.com/vertex-ai/docs/generative-ai/learn/models#foundation_models):
- [ ] gemini-pro
- [ ] PaLM-Chat-Bison-001

[Mistral](https://docs.mistral.ai/platform/endpoints/):
- [ ] Mistral Medium

[Perplexity](https://docs.perplexity.ai/reference/post_chat_completions):
- [ ] pplx-70b-online
- [ ] pplx-7b-online

**Comment by ProKil** [comment]
@clementou I feel like it is not scalable to add more models to `LLM_Name`. Since there are libraries like LiteLLM which converts all models to a uniform api, we can should allow using custom endpoints and not overflow our code with a long list of LLMs we support. 

@lwaekfjlk @ruiyiw @Jasonqi146 @sharonwx54 worked on adding a custom model which could support all possible endpoints. There's no need to do repetitive efforts.

**Comment by XuhuiZhou** [comment]
Thanks @ProKil! @clementou Feel free to chat with people to figure out their solutions! You can directly post Qs in the `sotopia-technical` channel (or simply communicate here; i just find people usually don't check this haha)
