### ISSUE TITLE
[FEAT]: Deprecating LLM Names

### ISSUE THREAD

**Issue by ProKil** [sotopia-lab/sotopia#43]
### Description

As we are moving towards LiteLLM as the unified backend for all LLM calls, and use runtime checking for verifying llm names. Let's remove `LLM_Name` type.

**Comment by XuhuiZhou** [comment]
We have some special agent names that need to be especially careful:
`human` `redis`

LiteLLM won't handle those situation

**Comment by ProKil** [comment]
The question is whether we want to keep a way to statically check the validity of the LLM's name? We can also create a router to handle model names not accepted by LiteLLM.

**Comment by XuhuiZhou** [comment]
We are keeping the LLM_Name
