### ISSUE TITLE
[BUG]: Need to update sotopia episode data

### ISSUE THREAD

**Issue by lwaekfjlk** [sotopia-lab/sotopia#47]
### Description of the bug

The serialization output has rewards in the jsonlines. However, in the released huggingface dataset, it does not have reward attributes.

### Steps To Reproduce

https://huggingface.co/datasets/cmu-lti/sotopia/tree/main No rewards

**Comment by lwaekfjlk** [comment]
Also, I think we can serialize all of our sotopia-pi data from the database use this part of serialization code. @ruiyiw @sharonwx54

**Comment by sharonwx54** [comment]
will fix it soon.

**Comment by lwaekfjlk** [comment]
@sharonwx54  I think I am pointing to sotopia not sotopia-pi data. Both needs to be updated.

**Comment by sharonwx54** [comment]
> @sharonwx54 I think I am pointing to sotopia not sotopia-pi data. Both needs to be updated.

Yes, I did upload latest data with rewards for both. They are in separate PR under sotopia and sotopia-pi.

**Comment by lwaekfjlk** [comment]
nice~
