### ISSUE TITLE
[FEAT]: Improved error msg

### ISSUE THREAD

**Issue by XuhuiZhou** [sotopia-lab/sotopia#62]
### Description

We currently have no error msg when 
https://github.com/sotopia-lab/sotopia/blob/c3436baf5fc8d7cfe9e72db76fe9a7ba06c06a05/sotopia/generation_utils/generate.py#L706

fails.

I suggest we get rid of the try, except behavior

**Comment by ProKil** [comment]
Then how should we handle the exception? Can you propose a taxonomy of different kinds of exceptions?

**Comment by XuhuiZhou** [comment]
https://github.com/sotopia-lab/sotopia/blob/c3436baf5fc8d7cfe9e72db76fe9a7ba06c06a05/sotopia/generation_utils/generate.py#L448

I think we should really focus on this function instead and give error msg for each step if it fails

**Comment by ProKil** [comment]
Yeah, so what are the possible errors and how we should deal with each of them?

**Comment by ProKil** [comment]
For examples, we should deal with parsing errors (not outputting correct schema) and API errors (rate limit, end point not available) differently.
