### ISSUE TITLE
[FEAT]: Release database and load database objects

### ISSUE THREAD

**Issue by weikang-wang** [sotopia-lab/sotopia#7]
### Description

And could you release all episodes which were generated by your experiments? Thank you.

**Comment by ProKil** [comment]
Hi @weikang-wang,

Thanks for your issue. I am still trying to figure out the best way to share them and make them more accessible. 

However, you could now download the whole database checkpoint which includes characters/scenarios/episodes/logs/etc. via the following command:

```bash
curl -L https://cmu.box.com/shared/static/xiivc5z8rnmi1zr6vmk1ohxslylvynur --output <your-data-folder>/sotopia-dump.rdb
```

Although this file is not directly readable, you could browse it through the starting a redis server. The are various ways to do that, the easiest of which is through `docker`. 

```bash
docker run --name redis-stack -p 6379:6379 -p 8001:8001 -v <your-data-folder>:/data redis/redis-stack:latest
```

This will set up a server on your machine. You will be able to browse all data on`http://localhost:8001`. 

Let me know if you are able to follow all previous steps.

**Comment by ProKil** [comment]
Feel free to reopen if you have further questions.

**Comment by weikang-wang** [comment]
> Hi @weikang-wang,
> 
> Thanks for your issue. I am still trying to figure out the best way to share them and make them more accessible.
> 
> However, you could now download the whole database checkpoint which includes characters/scenarios/episodes/logs/etc. via the following command:
> 
> ```shell
> curl -L https://cmu.box.com/shared/static/xiivc5z8rnmi1zr6vmk1ohxslylvynur --output <your-data-folder>/sotopia-dump.rdb
> ```
> 
> Although this file is not directly readable, you could browse it through the starting a redis server. The are various ways to do that, the easiest of which is through `docker`.
> 
> ```shell
> docker run --name redis-stack -p 6379:6379 -p 8001:8001 -v <your-data-folder>:/data redis/redis-stack:latest
> ```
> 
> This will set up a server on your machine. You will be able to browse all data on`http://localhost:8001`.
> 
> Let me know if you are able to follow all previous steps.

Sorry，but I can't download the whole database checkpoint.
<img width="1137" alt="截屏2023-11-11 17 02 13" src="https://github.com/sotopia-lab/sotopia/assets/18588005/70174dcc-2453-4bb2-b669-74ac706d955e">

**Comment by weikang-wang** [comment]
> Hi @weikang-wang,
> 
> Thanks for your issue. I am still trying to figure out the best way to share them and make them more accessible.
> 
> However, you could now download the whole database checkpoint which includes characters/scenarios/episodes/logs/etc. via the following command:
> 
> ```shell
> curl -L https://cmu.box.com/shared/static/xiivc5z8rnmi1zr6vmk1ohxslylvynur --output <your-data-folder>/sotopia-dump.rdb
> ```
> 
> Although this file is not directly readable, you could browse it through the starting a redis server. The are various ways to do that, the easiest of which is through `docker`.
> 
> ```shell
> docker run --name redis-stack -p 6379:6379 -p 8001:8001 -v <your-data-folder>:/data redis/redis-stack:latest
> ```
> 
> This will set up a server on your machine. You will be able to browse all data on`http://localhost:8001`.
> 
> Let me know if you are able to follow all previous steps.

Sorry, I followed your instructions. But I can not find any data.

<img width="1621" alt="截屏2023-11-12 12 44 31" src="https://github.com/sotopia-lab/sotopia/assets/18588005/1d8c6463-727b-49c2-841c-22e8e1635070">

**Comment by ProKil** [comment]
I think the problem is the filename. Could you try renaming the downloaded file as `dump.rdb`, i.e. change the `sotopia-dump.rdb` to `dump.rdb`? @sharonwx54 could you help double check if this works since you are also working on this?

**Comment by XuhuiZhou** [comment]
The command is not really working here, looks like the dump.rdb will be rewritten/cleared once I ran the second command

**Comment by sharonwx54** [comment]
> http://localhost:8001

Sorry just saw this @. I have the same issue, after running the two lines, there isn't any data in redis.

**Comment by ProKil** [comment]
This is strange since I tested it on both Mac and Linux.

Here are the steps I took (on Mac):

1. Download the dump with curl:

```bash
curl -L https://cmu.box.com/shared/static/xiivc5z8rnmi1zr6vmk1ohxslylvynur --output ~/Downloads/sotopia-dump.rdb
```

2. Copy and rename the dump:

```bash
mkdir ~/redis-data
cp  ~/Downloads/sotopia-dump.rdb ~/redis-data/dump.rdb
```

3. Install docker and start the server:


```bash
brew install --cask docker
sudo docker run --name redis-stack -p 6379:6379 -p 8001:8001 -v ./redis-data/:/data/ redis/redis-stack:latest
```

The output of the last command indicates successful loading:


```
9:C 13 Nov 2023 01:07:32.337 * oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
9:C 13 Nov 2023 01:07:32.337 * Redis version=7.2.3, bits=64, commit=00000000, modified=0, pid=9, just started
...
9:M 13 Nov 2023 01:07:33.539 * DB loaded from disk: 1.198 seconds
9:M 13 Nov 2023 01:07:33.539 * Ready to accept connections tcp
```

And I have 15k keys in the database. 

<img width="1719" alt="Screenshot 2023-11-12 at 8 13 54 PM" src="https://github.com/sotopia-lab/sotopia/assets/16367382/eab15768-efa7-4e59-8c6f-20042234973e">

On linux, the procedure is similar and the resulting database is exactly the same. Please post the exact commands you ran if you still cannot load the whole database.

**Comment by sharonwx54** [comment]
> This is strange since I tested it on both Mac and Linux.
> 
> Here are the exact steps I took (on Mac):
> 
> 1. Download the dump with curl:
> 
> ```shell
> curl -L https://cmu.box.com/shared/static/xiivc5z8rnmi1zr6vmk1ohxslylvynur --output ~/Downloads/sotopia-dump.rdb
> ```
> 
> 2. Copy and rename the dump:
> 
> ```shell
> mkdir ~/redis-data
> cp  ~/Downloads/sotopia-dump.rdb ~/redis-data/dump.rdb
> ```
> 
> 3. Install docker and start the server:
> 
> ```shell
> brew install --cask docker
> sudo docker run --name redis-stack -p 6379:6379 -p 8001:8001 -v ./redis-data/:/data/ redis/redis-stack:latest
> ```
> 
> The output of the last command indicates successful loading:
> 
> ```
> 9:C 13 Nov 2023 01:07:32.337 * oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
> 9:C 13 Nov 2023 01:07:32.337 * Redis version=7.2.3, bits=64, commit=00000000, modified=0, pid=9, just started
> ...
> 9:M 13 Nov 2023 01:07:33.539 * DB loaded from disk: 1.198 seconds
> 9:M 13 Nov 2023 01:07:33.539 * Ready to accept connections tcp
> ```
> 
> And I have 15k keys in the database.
> 
> <img alt="Screenshot 2023-11-12 at 8 13 54 PM" width="1719" src="https://user-images.githubusercontent.com/16367382/282339990-eab15768-efa7-4e59-8c6f-20042234973e.png">
> On linux, the procedure is similar and the resulting database is exactly the same. Please post the exact commands you ran if you still cannot load the whole database.

I followed all steps as above, and the commands are exactly the same as what you provided. I get this error message at the last step:

9:M 13 Nov 2023 04:03:21.323 * <timeseries> RedisTimeSeries version 11009, git_sha=6782c54bcb7dddeb6669f24cd5113dad64a4b03d
9:M 13 Nov 2023 04:03:21.323 * <timeseries> Redis version found by RedisTimeSeries : 7.2.3 - oss
9:M 13 Nov 2023 04:03:21.323 * <timeseries> loaded default CHUNK_SIZE_BYTES policy: 4096
9:M 13 Nov 2023 04:03:21.323 * <timeseries> loaded server DUPLICATE_POLICY: block
9:M 13 Nov 2023 04:03:21.323 * <timeseries> Setting default series ENCODING to: compressed
9:M 13 Nov 2023 04:03:21.324 * <timeseries> Detected redis oss
9:M 13 Nov 2023 04:03:21.325 * Module 'timeseries' loaded from /opt/redis-stack/lib/redistimeseries.so
9:M 13 Nov 2023 04:03:21.330 * <ReJSON> Created new data type 'ReJSON-RL'
9:M 13 Nov 2023 04:03:21.331 * <ReJSON> version: 20607 git sha: unknown branch: unknown
9:M 13 Nov 2023 04:03:21.331 * <ReJSON> Exported RedisJSON_V1 API
9:M 13 Nov 2023 04:03:21.331 * <ReJSON> Exported RedisJSON_V2 API
9:M 13 Nov 2023 04:03:21.331 * <ReJSON> Exported RedisJSON_V3 API
9:M 13 Nov 2023 04:03:21.331 * <ReJSON> Exported RedisJSON_V4 API
9:M 13 Nov 2023 04:03:21.331 * <ReJSON> Exported RedisJSON_V5 API
9:M 13 Nov 2023 04:03:21.331 * <ReJSON> Enabled diskless replication
9:M 13 Nov 2023 04:03:21.331 * Module 'ReJSON' loaded from /opt/redis-stack/lib/rejson.so
9:M 13 Nov 2023 04:03:21.331 * <search> Acquired RedisJSON_V4 API
9:M 13 Nov 2023 04:03:21.332 * <bf> RedisBloom version 2.6.8 (Git=unknown)
9:M 13 Nov 2023 04:03:21.332 * Module 'bf' loaded from /opt/redis-stack/lib/redisbloom.so
9:M 13 Nov 2023 04:03:21.338 * <redisgears_2> Created new data type 'GearsType'
9:M 13 Nov 2023 04:03:21.339 * <redisgears_2> Detected redis oss
**9:M 13 Nov 2023 04:03:21.339 # <redisgears_2> could not initialize RedisAI_InitError**

**9:M 13 Nov 2023 04:03:21.340 * <redisgears_2> Failed loading RedisAI API.**
9:M 13 Nov 2023 04:03:21.340 * <redisgears_2> RedisGears v2.0.14, sha='7b124f80636f6b58007a6b7093d65b96a8c2d920', build_type='release', built_for='Linux-ubuntu22.04.arm64v8'.
9:M 13 Nov 2023 04:03:21.355 * <redisgears_2> Registered backend: js.
9:M 13 Nov 2023 04:03:21.362 * Module 'redisgears_2' loaded from /opt/redis-stack/lib/redisgears.so
9:M 13 Nov 2023 04:03:21.362 * Server initialized
9:M 13 Nov 2023 04:03:21.363 * Ready to accept connections tcp

**Comment by weikang-wang** [comment]
> This is strange since I tested it on both Mac and Linux.
> 
> Here are the exact steps I took (on Mac):
> 
> 1. Download the dump with curl:
> 
> ```shell
> curl -L https://cmu.box.com/shared/static/xiivc5z8rnmi1zr6vmk1ohxslylvynur --output ~/Downloads/sotopia-dump.rdb
> ```
> 
>  2. Copy and rename the dump:
> 
> ```shell
> mkdir ~/redis-data
> cp  ~/Downloads/sotopia-dump.rdb ~/redis-data/dump.rdb
> ```
> 
> 3. Install docker and start the server:
> 
> ```shell
> brew install --cask docker
> sudo docker run --name redis-stack -p 6379:6379 -p 8001:8001 -v ./redis-data/:/data/ redis/redis-stack:latest
> ```
> 
> The output of the last command indicates successful loading:
> 
> ```
> 9:C 13 Nov 2023 01:07:32.337 * oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
> 9:C 13 Nov 2023 01:07:32.337 * Redis version=7.2.3, bits=64, commit=00000000, modified=0, pid=9, just started
> ...
> 9:M 13 Nov 2023 01:07:33.539 * DB loaded from disk: 1.198 seconds
> 9:M 13 Nov 2023 01:07:33.539 * Ready to accept connections tcp
> ```
> 
> And I have 15k keys in the database.
> 
> <img alt="Screenshot 2023-11-12 at 8 13 54 PM" width="1719" src="https://user-images.githubusercontent.com/16367382/282339990-eab15768-efa7-4e59-8c6f-20042234973e.png">
> On linux, the procedure is similar and the resulting database is exactly the same. Please post the exact commands you ran if you still cannot load the whole database.

It worked. Thank you. 
And if I want to export json files from Redis, how to do that ?

**Comment by ProKil** [comment]
@weikang-wang the canonical way we recommend is to use `redis-om` https://github.com/redis/redis-om-python to load (and validate) `pydantic` objects. This is the type-safe and pythonic way to interact with redis database. You can find all definitions of pydantic classes under `sotopia.database`, e.g. if you want to load all `EpisodeLog`, you can do

```python

from sotopia.database import EpisodeLog

ids = EpisodeLog.all_pks()
all_episode_logs = [EpisodeLog.get(episode_id) for episode_id in ids]

# convert to json, please refer to pydantic doc (v1.10) for serialization methods
all_episode_json = [episode_log.json() for episode_log in all_episode_logs]
```

The unsupported way is to dump the redis database to JSON files. There are generic libraries that should work, e.g. https://github.com/delano/redis-dump. However, we don't maintain or use those libraries. Please raise an issue in their libraries if you encounter any issues.

**Comment by ProKil** [comment]
@sharonwx54 I am not sure why it doesn't work. Could you check if [this stackoverflow post](https://stackoverflow.com/questions/76928167/how-to-migrate-redis-rdb-file-created-with-a-module-to-a-deployment-without-that) is related?

**Comment by ProKil** [comment]
After discussing with @sharonwx54 offline, it seems the the above instruction works. I will update the documentation with it. 

Feel free to reopen this issue.

**Comment by ProKil** [comment]
@TigerHix Thanks!
