### ISSUE TITLE
[FEAT]: mypy workflow testing speed can be optimized

### ISSUE THREAD

**Issue by lwaekfjlk** [sotopia-lab/sotopia#79]
### Description

Do we need to install --all-extras for mypy testing? I think it would take a lot of time. Only typing-related packages are required.

**Comment by ProKil** [comment]
Feel free to open a PR that removes `--all-extra`

**Comment by ProKil** [comment]
Fixed in #80

**Comment by lwaekfjlk** [comment]
nice!

**Comment by lwaekfjlk** [comment]
@ProKil  do you have any other suggestions on saving CI time with workflow. I faced a exceeding limit of 2000 min when running another codebase.

**Comment by ProKil** [comment]
One way is to limit CI to PRs. We could change mypy to pyright to save time, but I have not tested that yet.

**Comment by lwaekfjlk** [comment]
thanks. good to hear.

**Comment by ProKil** [comment]
There are several things that we could optimize including using a docker that has mypy and other tools pre-installed, and use local cache. You can also use [self-hosted test runners](https://docs.github.com/en/actions/hosting-your-own-runners/managing-self-hosted-runners/about-self-hosted-runners) and another tip I just found is that you can easily test run your commit before pushing using this https://github.com/nektos/act?tab=readme-ov-file. Maybe we should add this tip to the contribution guide.

**Comment by lwaekfjlk** [comment]
sounds good. Good to know all of these. I am trying to update my project-template to optimize its CI time.

**Comment by lwaekfjlk** [comment]
@ProKil I personally find that act is kind of not so easy to use? Should we add this into the contribution guide?

**Comment by ProKil** [comment]
Already improved in https://github.com/sotopia-lab/sotopia/blob/7de34af7b52aadf85c5c4302e660f745032caff8/.github/workflows/mypy.yml#L7-L17

**Comment by ProKil** [comment]
> @ProKil I personally find that act is kind of not so easy to use? Should we add this into the contribution guide?

Does "act" mean "agent.act"?
