### ISSUE TITLE
Seeking for help on running the Sotopia experiment code on server

### ISSUE THREAD

**Issue by Rubywong123** [sotopia-lab/sotopia#8]
# Problem Description

Hi! And thanks for your amazing work!
The problem we struggled at is, after setting up the environments as well as the Redis server, we still failed at connecting the Linux server to the Redis server. Specifically it just keeps reporting **redis.exceptions.timeouterror: timeout connecting to server**. 

The code is running well on my local machine (also went well when I ran the redis server on one laptop and ran the Sotopia experiment code on another laptop). 

## Steps to Reproduce
1. `git clone` the repo onto the server
2. configure the virtual environment as written in README.md
3. build the redis server on the local machine, as detailed in [the issue](https://github.com/sotopia-lab/sotopia/issues/7#issuecomment-1807335078). Set the `REDIS_OM_URL=redis://@IPaddress:6379` 
4. run 
```python examples/experiment_eval.py --gin_file sotopia_conf/generation_utils_conf/generate.gin --gin_file sotopia_conf/server_conf/server.gin --gin_file sotopia_conf/run_async_server_in_batch.gin '--gin.ENV_IDS=["01H7VFHPDZVVCDZR3AARA547CY"]' '--gin.AGENT1_MODEL="gpt-4"' '--gin.BATCH_SIZE=20' '--gin.PUSH_TO_DB=False' '--gin.TAG="test"'```

## Expected Behavior
It should work normally.

## Actual Behavior
On another laptop it perfectly works, but on Linux server it cannot successfully connect to the redis server.

## Environment
- Operating System: Linux/Mac

Thanks a lot!

**Comment by ProKil** [comment]
@Rubywong123 You can use this command to test redis connection: `python -c "from redis_om import get_redis_connection; assert get_redis_connection().ping()"`

Thanks for your issue. There could be multiple possible reasons depending on your network setup. To debug, maybe you can first test whether the port 6379 is accessible from your laptop. A simple way: `python -m http.server 6379` and then visit your ip address: 'http://IPaddress:6379'
