### ISSUE TITLE
[FEAT]: Remove Pandas dependency

### ISSUE THREAD

**Issue by ProKil** [sotopia-lab/sotopia#82]
### Description

Since pandas is widely used and often has other dependency restrictions, e.g. on Google Colab, we would encounter

```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
cudf-cu12 24.4.1 requires pandas<2.2.2dev0,>=2.0, but you have pandas 2.2.2 which is incompatible.
google-colab 1.0.0 requires pandas==2.0.3, but you have pandas 2.2.2 which is incompatible.
```

which doesn't prevent us from install `sotopia==0.0.7`, but it is still annoying. The only use of pandas in our package is converting a dict of list into a csv file, which could be done with various other, even standard libraries. 

Related to the plan mentioned in #80.

**Comment by XuhuiZhou** [comment]
I agree
