### ISSUE TITLE
[FEAT]: update contribution readme and sync with docs webpage

### ISSUE THREAD

**Issue by XuhuiZhou** [sotopia-lab/sotopia#85]
### Description

* The ## contribution section seems to be outdated
* Is there any particular reasons that we don't include the readme page in the doc? (It would be convenient if we only need to maintain one version)

**Comment by ProKil** [comment]
I would suggest we 

1. add a contribution page in the doc and leave a link to it in the readme
2. remove most of contents in readme with only the simplest examples. 

We can however, add a demo, even as simple as a screen recording with a terminal view, to the readme page. 

I think the readme page serves a quick intro to show what this library aims at, and the docs is the must read for anybody who wants to use our library. Just to give two examples:

1. https://github.com/pydantic/pydantic
2. https://github.com/tinygrad/tinygrad?tab=readme-ov-file

**Comment by XuhuiZhou** [comment]
Another example could be:
1. https://github.com/camel-ai/camel

They seem to facilitate an active community there

**Comment by XuhuiZhou** [comment]
The crewAI one looks pretty cool too:
https://www.crewai.com/
