### ISSUE TITLE
[BUG]: FileNotFoundError: [Errno 2] No such file or directory: '/Users/wangweikang/PycharmProjects/sotopia/logs/00_00_07_12_2023_5ee80d957b58ff5a82447f6d689c351b5a7a6f35.log'`

### ISSUE THREAD

**Issue by weikang-wang** [sotopia-lab/sotopia#9]
### Description of the bug

I successfully connected to Redis server and installed it. 
And I run `python -m sotopia_conf.server --gin_file="sotopia_conf/server_conf/server.gin" --gin_file="sotopia_conf/generation_utils_conf/generate.gin"`
It worked very well.
But when I ran python examples/experiment_eval.py , an error occurred.

`(sotopia) wangweikang@wangweikangdeMacBook-Pro sotopia % python examples/experiment_eval.py \
 --gin_file sotopia_conf/generation_utils_conf/generate.gin \
 --gin_file sotopia_conf/server_conf/server.gin \
 --gin_file sotopia_conf/run_async_server_in_batch.gin \
 '--gin.ENV_IDS=["01H7VFHPDZVVCDZR3AARA547CY"]' \
 '--gin.AGENT1_MODEL="gpt-4"' \
 '--gin.BATCH_SIZE=20' \
 '--gin.PUSH_TO_DB=False' \
 '--gin.TAG="test"'
/Users/wangweikang/Applications/Anaconda/anaconda3/envs/sotopia/lib/python3.11/site-packages/beartype/_util/hint/pep/utilpeptest.py:311: BeartypeDecorHintPep585DeprecationWarning: PEP 484 type hint typing.Sequence[sotopia.agents.base_agent.BaseAgent[sotopia.messages.message_classes.Observation, sotopia.messages.message_classes.AgentAction]] deprecated by PEP 585. This hint is scheduled for removal in the first Python version released after October 5th, 2025. To resolve this, import this hint from "beartype.typing" rather than "typing". For further commentary and alternatives, see also:
    https://beartype.readthedocs.io/en/latest/api_roar/#pep-585-deprecations
  warn(
Traceback (most recent call last):
  File "/Users/wangweikang/PycharmProjects/sotopia/examples/experiment_eval.py", line 57, in <module>
    FileHandler(
  File "/Users/wangweikang/Applications/Anaconda/anaconda3/envs/sotopia/lib/python3.11/logging/__init__.py", line 1181, in __init__
    StreamHandler.__init__(self, self._open())
                                 ^^^^^^^^^^^^
  File "/Users/wangweikang/Applications/Anaconda/anaconda3/envs/sotopia/lib/python3.11/logging/__init__.py", line 1213, in _open
    return open_func(self.baseFilename, self.mode,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/Users/wangweikang/PycharmProjects/sotopia/logs/00_00_07_12_2023_5ee80d957b58ff5a82447f6d689c351b5a7a6f35.log'`

### Steps To Reproduce

python examples/experiment_eval.py \
 --gin_file sotopia_conf/generation_utils_conf/generate.gin \
 --gin_file sotopia_conf/server_conf/server.gin \
 --gin_file sotopia_conf/run_async_server_in_batch.gin \
 '--gin.ENV_IDS=["01H7VFHPDZVVCDZR3AARA547CY"]' \
 '--gin.AGENT1_MODEL="gpt-4"' \
 '--gin.BATCH_SIZE=20' \
 '--gin.PUSH_TO_DB=False' \
 '--gin.TAG="test"'

### Environment
MacOS

**Comment by weikang-wang** [comment]
> Thanks @weikang-wang Please first `mkdir logs` under the `sotopia` folder as the temporary solution.

Thank you , it worked.But there are still a problem. 

> (sotopia) wangweikang@wangweikangdeMacBook-Pro sotopia % /bin/zsh /Users/wangweikang/PycharmProjects/sotopia/experiment_test.sh
/Users/wangweikang/Applications/Anaconda/anaconda3/envs/sotopia/lib/python3.11/site-packages/beartype/_util/hint/pep/utilpeptest.py:311: BeartypeDecorHintPep585DeprecationWarning: PEP 484 type hint typing.Sequence[sotopia.agents.base_agent.BaseAgent[sotopia.messages.message_classes.Observation, sotopia.messages.message_classes.AgentAction]] deprecated by PEP 585. This hint is scheduled for removal in the first Python version released after October 5th, 2025. To resolve this, import this hint from "beartype.typing" rather than "typing". For further commentary and alternatives, see also:
    https://beartype.readthedocs.io/en/latest/api_roar/#pep-585-deprecations
  warn(
Rewritten gin arg: --gin_bindings=ENV_IDS = ["01H7VFHPDZVVCDZR3AARA547CY"]
Rewritten gin arg: --gin_bindings=AGENT1_MODEL = "gpt-3.5-turbo"
Rewritten gin arg: --gin_bindings=AGENT2_MODEL = "gpt-3.5-turbo"
Rewritten gin arg: --gin_bindings=BATCH_SIZE = 20
Rewritten gin arg: --gin_bindings=PUSH_TO_DB = False
Rewritten gin arg: --gin_bindings=TAG = "test"
[15:07:04] INFO     [15:07:04] - INFO - root - Gin Configuration:                                                                                                          gin_utils.py:55
I1211 15:07:04.495892 7915626176 gin_utils.py:55] Gin Configuration:
           INFO     [15:07:04] - INFO - root - from __gin__ import dynamic_registration                                                                                    gin_utils.py:57
I1211 15:07:04.498666 7915626176 gin_utils.py:57] from __gin__ import dynamic_registration
           INFO     [15:07:04] - INFO - root - import __main__ as main_script                                                                                              gin_utils.py:57
I1211 15:07:04.499250 7915626176 gin_utils.py:57] import __main__ as main_script
           INFO     [15:07:04] - INFO - root - import sotopia.envs.evaluators as evaluators                                                                                gin_utils.py:57
I1211 15:07:04.502424 7915626176 gin_utils.py:57] import sotopia.envs.evaluators as evaluators
           INFO     [15:07:04] - INFO - root - import sotopia.generation_utils.generate as generate                                                                        gin_utils.py:57
I1211 15:07:04.502939 7915626176 gin_utils.py:57] import sotopia.generation_utils.generate as generate
           INFO     [15:07:04] - INFO - root - import sotopia.server as server                                                                                             gin_utils.py:57
I1211 15:07:04.503413 7915626176 gin_utils.py:57] import sotopia.server as server
           INFO     [15:07:04] - INFO - root -                                                                                                                             gin_utils.py:57
I1211 15:07:04.503957 7915626176 gin_utils.py:57] 
           INFO     [15:07:04] - INFO - root - # Macros:                                                                                                                   gin_utils.py:57
I1211 15:07:04.504391 7915626176 gin_utils.py:57] # Macros:
           INFO     [15:07:04] - INFO - root - # ==============================================================================                                            gin_utils.py:57
I1211 15:07:04.505059 7915626176 gin_utils.py:57] # ==============================================================================
           INFO     [15:07:04] - INFO - root - ACTION_ORDER = 'round-robin'                                                                                                gin_utils.py:57
I1211 15:07:04.505496 7915626176 gin_utils.py:57] ACTION_ORDER = 'round-robin'
           INFO     [15:07:04] - INFO - root - AGENT1_MODEL = 'gpt-3.5-turbo'                                                                                              gin_utils.py:57
I1211 15:07:04.505908 7915626176 gin_utils.py:57] AGENT1_MODEL = 'gpt-3.5-turbo'
           INFO     [15:07:04] - INFO - root - AGENT2_MODEL = 'gpt-3.5-turbo'                                                                                              gin_utils.py:57
I1211 15:07:04.506286 7915626176 gin_utils.py:57] AGENT2_MODEL = 'gpt-3.5-turbo'
           INFO     [15:07:04] - INFO - root - BATCH_SIZE = 20                                                                                                             gin_utils.py:57
I1211 15:07:04.506651 7915626176 gin_utils.py:57] BATCH_SIZE = 20
           INFO     [15:07:04] - INFO - root - ENV_IDS = ['01H7VFHPDZVVCDZR3AARA547CY']                                                                                    gin_utils.py:57
I1211 15:07:04.507019 7915626176 gin_utils.py:57] ENV_IDS = ['01H7VFHPDZVVCDZR3AARA547CY']
           INFO     [15:07:04] - INFO - root - MAX_RETRIES = 6                                                                                                             gin_utils.py:57
I1211 15:07:04.507393 7915626176 gin_utils.py:57] MAX_RETRIES = 6
           INFO     [15:07:04] - INFO - root - MODEL_NAMES = {'agent1': %AGENT1_MODEL, 'agent2': %AGENT2_MODEL, 'env': 'gpt-4'}                                            gin_utils.py:57
I1211 15:07:04.507742 7915626176 gin_utils.py:57] MODEL_NAMES = {'agent1': %AGENT1_MODEL, 'agent2': %AGENT2_MODEL, 'env': 'gpt-4'}
           INFO     [15:07:04] - INFO - root - PUSH_TO_DB = False                                                                                                          gin_utils.py:57
I1211 15:07:04.508172 7915626176 gin_utils.py:57] PUSH_TO_DB = False
           INFO     [15:07:04] - INFO - root - TAG = 'test'                                                                                                                gin_utils.py:57
I1211 15:07:04.508537 7915626176 gin_utils.py:57] TAG = 'test'
           INFO     [15:07:04] - INFO - root - TAG_TO_CHECK_EXISTING_EPISODES = None                                                                                       gin_utils.py:57
I1211 15:07:04.508877 7915626176 gin_utils.py:57] TAG_TO_CHECK_EXISTING_EPISODES = None
           INFO     [15:07:04] - INFO - root - VERBOSE = False                                                                                                             gin_utils.py:57
I1211 15:07:04.509258 7915626176 gin_utils.py:57] VERBOSE = False
           INFO     [15:07:04] - INFO - root -                                                                                                                             gin_utils.py:57
I1211 15:07:04.509602 7915626176 gin_utils.py:57] 
           INFO     [15:07:04] - INFO - root - # Parameters for evaluators.ReachGoalLLMEvaluator.__acall__:                                                                gin_utils.py:57
I1211 15:07:04.509914 7915626176 gin_utils.py:57] # Parameters for evaluators.ReachGoalLLMEvaluator.__acall__:
           INFO     [15:07:04] - INFO - root - # ==============================================================================                                            gin_utils.py:57
I1211 15:07:04.510308 7915626176 gin_utils.py:57] # ==============================================================================
           INFO     [15:07:04] - INFO - root - evaluators.ReachGoalLLMEvaluator.__acall__.temperature = 0.0                                                                gin_utils.py:57
I1211 15:07:04.510678 7915626176 gin_utils.py:57] evaluators.ReachGoalLLMEvaluator.__acall__.temperature = 0.0
           INFO     [15:07:04] - INFO - root -                                                                                                                             gin_utils.py:57
I1211 15:07:04.511076 7915626176 gin_utils.py:57] 
           INFO     [15:07:04] - INFO - root - # Parameters for main_script._iterate_env_agent_combo_not_in_db:                                                            gin_utils.py:57
I1211 15:07:04.511387 7915626176 gin_utils.py:57] # Parameters for main_script._iterate_env_agent_combo_not_in_db:
           INFO     [15:07:04] - INFO - root - # ==============================================================================                                            gin_utils.py:57
I1211 15:07:04.511785 7915626176 gin_utils.py:57] # ==============================================================================
           INFO     [15:07:04] - INFO - root - main_script._iterate_env_agent_combo_not_in_db.env_ids = %ENV_IDS                                                           gin_utils.py:57
I1211 15:07:04.512139 7915626176 gin_utils.py:57] main_script._iterate_env_agent_combo_not_in_db.env_ids = %ENV_IDS
           INFO     [15:07:04] - INFO - root - main_script._iterate_env_agent_combo_not_in_db.tag = \                                                                      gin_utils.py:57
I1211 15:07:04.512560 7915626176 gin_utils.py:57] main_script._iterate_env_agent_combo_not_in_db.tag = \
           INFO     [15:07:04] - INFO - root -     %TAG_TO_CHECK_EXISTING_EPISODES                                                                                         gin_utils.py:57
I1211 15:07:04.512953 7915626176 gin_utils.py:57]     %TAG_TO_CHECK_EXISTING_EPISODES
           INFO     [15:07:04] - INFO - root -                                                                                                                             gin_utils.py:57
I1211 15:07:04.513314 7915626176 gin_utils.py:57] 
           INFO     [15:07:04] - INFO - root - # Parameters for generate.agenerate_action:                                                                                 gin_utils.py:57
I1211 15:07:04.513626 7915626176 gin_utils.py:57] # Parameters for generate.agenerate_action:
           INFO     [15:07:04] - INFO - root - # ==============================================================================                                            gin_utils.py:57
I1211 15:07:04.513993 7915626176 gin_utils.py:57] # ==============================================================================
           INFO     [15:07:04] - INFO - root - generate.agenerate_action.temperature = 1.0                                                                                 gin_utils.py:57
I1211 15:07:04.514392 7915626176 gin_utils.py:57] generate.agenerate_action.temperature = 1.0
           INFO     [15:07:04] - INFO - root -                                                                                                                             gin_utils.py:57
I1211 15:07:04.514767 7915626176 gin_utils.py:57] 
           INFO     [15:07:04] - INFO - root - # Parameters for generate.agenerate_env_profile:                                                                            gin_utils.py:57
I1211 15:07:04.515084 7915626176 gin_utils.py:57] # Parameters for generate.agenerate_env_profile:
           INFO     [15:07:04] - INFO - root - # ==============================================================================                                            gin_utils.py:57
I1211 15:07:04.515449 7915626176 gin_utils.py:57] # ==============================================================================
           INFO     [15:07:04] - INFO - root - generate.agenerate_env_profile.model_name = 'gpt-3.5-turbo'                                                                 gin_utils.py:57
I1211 15:07:04.515815 7915626176 gin_utils.py:57] generate.agenerate_env_profile.model_name = 'gpt-3.5-turbo'
           INFO     [15:07:04] - INFO - root -                                                                                                                             gin_utils.py:57
I1211 15:07:04.516201 7915626176 gin_utils.py:57] 
           INFO     [15:07:04] - INFO - root - # Parameters for generate.obtain_chain:                                                                                     gin_utils.py:57
I1211 15:07:04.516511 7915626176 gin_utils.py:57] # Parameters for generate.obtain_chain:
           INFO     [15:07:04] - INFO - root - # ==============================================================================                                            gin_utils.py:57
I1211 15:07:04.516870 7915626176 gin_utils.py:57] # ==============================================================================
           INFO     [15:07:04] - INFO - root - generate.obtain_chain.max_retries = %MAX_RETRIES                                                                            gin_utils.py:57
I1211 15:07:04.517221 7915626176 gin_utils.py:57] generate.obtain_chain.max_retries = %MAX_RETRIES
           INFO     [15:07:04] - INFO - root -                                                                                                                             gin_utils.py:57
I1211 15:07:04.517587 7915626176 gin_utils.py:57] 
           INFO     [15:07:04] - INFO - root - # Parameters for server.run_async_server:                                                                                   gin_utils.py:57
I1211 15:07:04.517894 7915626176 gin_utils.py:57] # Parameters for server.run_async_server:
           INFO     [15:07:04] - INFO - root - # ==============================================================================                                            gin_utils.py:57
I1211 15:07:04.518256 7915626176 gin_utils.py:57] # ==============================================================================
           INFO     [15:07:04] - INFO - root - server.run_async_server.action_order = %ACTION_ORDER                                                                        gin_utils.py:57
I1211 15:07:04.518613 7915626176 gin_utils.py:57] server.run_async_server.action_order = %ACTION_ORDER
           INFO     [15:07:04] - INFO - root - server.run_async_server.model_dict = \                                                                                      gin_utils.py:57
I1211 15:07:04.518985 7915626176 gin_utils.py:57] server.run_async_server.model_dict = \
           INFO     [15:07:04] - INFO - root -     {'agent1': 'gpt-3.5-turbo', 'agent2': 'gpt-3.5-turbo', 'env': 'gpt-4'}                                                  gin_utils.py:57
I1211 15:07:04.519351 7915626176 gin_utils.py:57]     {'agent1': 'gpt-3.5-turbo', 'agent2': 'gpt-3.5-turbo', 'env': 'gpt-4'}
           INFO     [15:07:04] - INFO - root - server.run_async_server.push_to_db = %PUSH_TO_DB                                                                            gin_utils.py:57
I1211 15:07:04.519749 7915626176 gin_utils.py:57] server.run_async_server.push_to_db = %PUSH_TO_DB
           INFO     [15:07:04] - INFO - root - server.run_async_server.tag = %TAG                                                                                          gin_utils.py:57
I1211 15:07:04.520122 7915626176 gin_utils.py:57] server.run_async_server.tag = %TAG
           INFO     [15:07:04] - INFO - root - server.run_async_server.using_async = True                                                                                  gin_utils.py:57
I1211 15:07:04.520482 7915626176 gin_utils.py:57] server.run_async_server.using_async = True
           INFO     [15:07:04] - INFO - root -                                                                                                                             gin_utils.py:57
I1211 15:07:04.520857 7915626176 gin_utils.py:57] 
           INFO     [15:07:04] - INFO - root - # Parameters for main_script.run_async_server_in_batch:                                                                     gin_utils.py:57
I1211 15:07:04.521166 7915626176 gin_utils.py:57] # Parameters for main_script.run_async_server_in_batch:
           INFO     [15:07:04] - INFO - root - # ==============================================================================                                            gin_utils.py:57
I1211 15:07:04.521544 7915626176 gin_utils.py:57] # ==============================================================================
           INFO     [15:07:04] - INFO - root - main_script.run_async_server_in_batch.batch_size = %BATCH_SIZE                                                              gin_utils.py:57
I1211 15:07:04.521894 7915626176 gin_utils.py:57] main_script.run_async_server_in_batch.batch_size = %BATCH_SIZE
           INFO     [15:07:04] - INFO - root - main_script.run_async_server_in_batch.model_names = %MODEL_NAMES                                                            gin_utils.py:57
I1211 15:07:04.522287 7915626176 gin_utils.py:57] main_script.run_async_server_in_batch.model_names = %MODEL_NAMES
           INFO     [15:07:04] - INFO - root - main_script.run_async_server_in_batch.tag = %TAG                                                                            gin_utils.py:57
I1211 15:07:04.522958 7915626176 gin_utils.py:57] main_script.run_async_server_in_batch.tag = %TAG
           INFO     [15:07:04] - INFO - root - main_script.run_async_server_in_batch.verbose = %VERBOSE                                                                    gin_utils.py:57
I1211 15:07:04.523576 7915626176 gin_utils.py:57] main_script.run_async_server_in_batch.verbose = %VERBOSE
**Running all envs in batch: 0it [00:00, ?it/s]**


It seems that it exited when runing for loop.

### Steps To Reproduce
python examples/experiment_eval.py
--gin_file sotopia_conf/generation_utils_conf/generate.gin
--gin_file sotopia_conf/server_conf/server.gin
--gin_file sotopia_conf/run_async_server_in_batch.gin
'--gin.ENV_IDS=["01H7VFHPDZVVCDZR3AARA547CY"]'
'--gin.AGENT1_MODEL="gpt-4"'
'--gin.BATCH_SIZE=20'
'--gin.PUSH_TO_DB=False'
'--gin.TAG="test"'

**Comment by ProKil** [comment]
@XuhuiZhou can you help reproduce this problem?

**Comment by XuhuiZhou** [comment]
@weikang-wang Once the database is loaded, you need to set the `TAG_TO_CHECK_EXISTING_EPISODES` to the corresponding tag to run the experiments. For example, here you should add `--gin.TAG_TO_CHECK_EXISTING_EPISODES="test"`

(Or change to another tag if "test" is already in the database)

See:
https://github.com/sotopia-lab/sotopia/blob/696e07e275336127b23b46983dd2e3f26445cd8e/sotopia_conf/run_async_server_in_batch.gin#L8

**Comment by weikang-wang** [comment]
> @weikang-wang Once the database is loaded, you need to set the `TAG_TO_CHECK_EXISTING_EPISODES` to the corresponding tag to run the experiments. For example, here you should add `--gin.TAG_TO_CHECK_EXISTING_EPISODES="test"`
> 
> (Or change to another tag if "test" is already in the database)
> 
> See:
> 
> https://github.com/sotopia-lab/sotopia/blob/696e07e275336127b23b46983dd2e3f26445cd8e/sotopia_conf/run_async_server_in_batch.gin#L8
> 
> Let me know if you have more qs!

Thanks, it seems that I can not run it if the episode already in database. So, how to push my own data to redis database and run it ?

**Comment by XuhuiZhou** [comment]
Yes, you simply need to use a different tag and it should work.
