### ISSUE TITLE
[BUG]: Tuturial failed? 

### ISSUE THREAD

**Issue by XuhuiZhou** [sotopia-lab/sotopia#91]
### Description of the bug

![image](https://github.com/sotopia-lab/sotopia/assets/20436061/6c8a9260-9596-4e9a-b2fe-b3d33cfde8e4)

### Steps To Reproduce

1. go to [1.2 Browsing sotopia data](https://colab.research.google.com/drive/1Gi2U3cA0KG1nekw1A0N0DZpx6gKrj8Nc?usp=sharing)

2. run all

**Comment by ProKil** [comment]
Thanks. This is a random error since the the task doesn't have corresponding episodes. Will be resolved in #90
